Add Lagoon Extras module.
govCMS/govcms8lagoon pull request #103
Opened 2019-10-23 02:21 UTC by steveworley

Lagoon Extras, a place where additional application glue code can be added to provide additional insight to sites running on the platform.

2019-11-11 22:42 UTC, srowlands commented on modules/lagoon/lagoon_extras/README.md
> +$config['lagoon_extras.settings']['verbose_logging']= getenv('GOVCMS_VERBOSE_LOGGING') ?: FALSE;
This is currently missing from settings file, so we have no way to enable via env var at the moment

2020-01-16 21:15 UTC, AlexSkrypnyk commented on modules/lagoon/lagoon_extras/src/File/FileSystem.php
> +      $this->logger->info("The file %uri was successfully unlinked", ['%uri' => $uri]);
should use single quotes

2020-01-16 21:23 UTC, AlexSkrypnyk requested changes
@steveworley 
We need to run PHPCS for this module as it currently violates Drupal coding standards.

Also, the module is missing tests.

2020-01-16 21:23 UTC, AlexSkrypnyk commented on modules/lagoon/lagoon_extras/src/File/FileSystem.php
> +        $this->logger->info('%backtrace', ['%backtrace' => json_encode(debug_backtrace())]);
do we want to limit `debug_backtrace()` to use `DEBUG_BACKTRACE_IGNORE_ARGS` to save the memory?

2020-01-16 21:23 UTC, AlexSkrypnyk commented on modules/lagoon/lagoon_extras/src/Form/SettingsForm.php
> +
empty lines

2020-01-16 21:23 UTC, AlexSkrypnyk commented on modules/lagoon/lagoon_extras/src/Form/SettingsForm.php
> +
class description is missing

2020-01-16 22:52 UTC, simesy commented
Looking for a little more info in the README on this module. In the past modules that live in govcms8lagoon have only been installed and then uninstalled. So they had no effect on the resulting config state. Having drupal modules in the image repo is an antipattern as far as I'm concerned but I've overlooked it in the past due to the fact the modules get uninstalled afterwards.

This module has routes and settings forms and such, so if it's installed we're relying on operations to uninstall it afterwards. Perhaps a note on how to add this module to config ignore so that it doesn't unintentionally effect config operations.

2021-04-13 04:58 UTC, closed without merging